// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: allocation.proto

package ds.smartbuilding.allocate;

public final class AllocateServiceImpl {
  private AllocateServiceImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_allocate_listofAttendeesRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_allocate_listofAttendeesRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_allocate_meetingRoomResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_allocate_meetingRoomResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020allocation.proto\022\010allocate\"1\n\026listofAt" +
      "tendeesRequest\022\027\n\017listOfAttendees\030\001 \001(\t\"" +
      "*\n\023meetingRoomResponse\022\023\n\013meetingRoom\030\001 " +
      "\001(\t2f\n\017AllocateService\022S\n\014allocateRoom\022 " +
      ".allocate.listofAttendeesRequest\032\035.alloc" +
      "ate.meetingRoomResponse\"\000(\001B2\n\031ds.smartb" +
      "uilding.allocateB\023AllocateServiceImplP\001b" +
      "\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_allocate_listofAttendeesRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_allocate_listofAttendeesRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_allocate_listofAttendeesRequest_descriptor,
        new java.lang.String[] { "ListOfAttendees", });
    internal_static_allocate_meetingRoomResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_allocate_meetingRoomResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_allocate_meetingRoomResponse_descriptor,
        new java.lang.String[] { "MeetingRoom", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
