// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: allocation.proto

package ds.smartbuilding.allocate;

public interface listofAttendeesRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:allocate.listofAttendeesRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string listOfAttendees = 1;</code>
   */
  java.lang.String getListOfAttendees();
  /**
   * <code>string listOfAttendees = 1;</code>
   */
  com.google.protobuf.ByteString
      getListOfAttendeesBytes();
}
