// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: allocation.proto

package ds.smartbuilding.allocate;

/**
 * Protobuf type {@code allocate.meetingRoomResponse}
 */
public  final class meetingRoomResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:allocate.meetingRoomResponse)
    meetingRoomResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use meetingRoomResponse.newBuilder() to construct.
  private meetingRoomResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private meetingRoomResponse() {
    meetingRoom_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private meetingRoomResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            meetingRoom_ = s;
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return ds.smartbuilding.allocate.AllocateServiceImpl.internal_static_allocate_meetingRoomResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return ds.smartbuilding.allocate.AllocateServiceImpl.internal_static_allocate_meetingRoomResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            ds.smartbuilding.allocate.meetingRoomResponse.class, ds.smartbuilding.allocate.meetingRoomResponse.Builder.class);
  }

  public static final int MEETINGROOM_FIELD_NUMBER = 1;
  private volatile java.lang.Object meetingRoom_;
  /**
   * <code>string meetingRoom = 1;</code>
   */
  public java.lang.String getMeetingRoom() {
    java.lang.Object ref = meetingRoom_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      meetingRoom_ = s;
      return s;
    }
  }
  /**
   * <code>string meetingRoom = 1;</code>
   */
  public com.google.protobuf.ByteString
      getMeetingRoomBytes() {
    java.lang.Object ref = meetingRoom_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      meetingRoom_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getMeetingRoomBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, meetingRoom_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getMeetingRoomBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, meetingRoom_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof ds.smartbuilding.allocate.meetingRoomResponse)) {
      return super.equals(obj);
    }
    ds.smartbuilding.allocate.meetingRoomResponse other = (ds.smartbuilding.allocate.meetingRoomResponse) obj;

    boolean result = true;
    result = result && getMeetingRoom()
        .equals(other.getMeetingRoom());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + MEETINGROOM_FIELD_NUMBER;
    hash = (53 * hash) + getMeetingRoom().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static ds.smartbuilding.allocate.meetingRoomResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ds.smartbuilding.allocate.meetingRoomResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ds.smartbuilding.allocate.meetingRoomResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ds.smartbuilding.allocate.meetingRoomResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ds.smartbuilding.allocate.meetingRoomResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ds.smartbuilding.allocate.meetingRoomResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ds.smartbuilding.allocate.meetingRoomResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ds.smartbuilding.allocate.meetingRoomResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static ds.smartbuilding.allocate.meetingRoomResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static ds.smartbuilding.allocate.meetingRoomResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static ds.smartbuilding.allocate.meetingRoomResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ds.smartbuilding.allocate.meetingRoomResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(ds.smartbuilding.allocate.meetingRoomResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code allocate.meetingRoomResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:allocate.meetingRoomResponse)
      ds.smartbuilding.allocate.meetingRoomResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ds.smartbuilding.allocate.AllocateServiceImpl.internal_static_allocate_meetingRoomResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ds.smartbuilding.allocate.AllocateServiceImpl.internal_static_allocate_meetingRoomResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ds.smartbuilding.allocate.meetingRoomResponse.class, ds.smartbuilding.allocate.meetingRoomResponse.Builder.class);
    }

    // Construct using ds.smartbuilding.allocate.meetingRoomResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      meetingRoom_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return ds.smartbuilding.allocate.AllocateServiceImpl.internal_static_allocate_meetingRoomResponse_descriptor;
    }

    @java.lang.Override
    public ds.smartbuilding.allocate.meetingRoomResponse getDefaultInstanceForType() {
      return ds.smartbuilding.allocate.meetingRoomResponse.getDefaultInstance();
    }

    @java.lang.Override
    public ds.smartbuilding.allocate.meetingRoomResponse build() {
      ds.smartbuilding.allocate.meetingRoomResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public ds.smartbuilding.allocate.meetingRoomResponse buildPartial() {
      ds.smartbuilding.allocate.meetingRoomResponse result = new ds.smartbuilding.allocate.meetingRoomResponse(this);
      result.meetingRoom_ = meetingRoom_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof ds.smartbuilding.allocate.meetingRoomResponse) {
        return mergeFrom((ds.smartbuilding.allocate.meetingRoomResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(ds.smartbuilding.allocate.meetingRoomResponse other) {
      if (other == ds.smartbuilding.allocate.meetingRoomResponse.getDefaultInstance()) return this;
      if (!other.getMeetingRoom().isEmpty()) {
        meetingRoom_ = other.meetingRoom_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      ds.smartbuilding.allocate.meetingRoomResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (ds.smartbuilding.allocate.meetingRoomResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object meetingRoom_ = "";
    /**
     * <code>string meetingRoom = 1;</code>
     */
    public java.lang.String getMeetingRoom() {
      java.lang.Object ref = meetingRoom_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        meetingRoom_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string meetingRoom = 1;</code>
     */
    public com.google.protobuf.ByteString
        getMeetingRoomBytes() {
      java.lang.Object ref = meetingRoom_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        meetingRoom_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string meetingRoom = 1;</code>
     */
    public Builder setMeetingRoom(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      meetingRoom_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string meetingRoom = 1;</code>
     */
    public Builder clearMeetingRoom() {
      
      meetingRoom_ = getDefaultInstance().getMeetingRoom();
      onChanged();
      return this;
    }
    /**
     * <code>string meetingRoom = 1;</code>
     */
    public Builder setMeetingRoomBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      meetingRoom_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:allocate.meetingRoomResponse)
  }

  // @@protoc_insertion_point(class_scope:allocate.meetingRoomResponse)
  private static final ds.smartbuilding.allocate.meetingRoomResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new ds.smartbuilding.allocate.meetingRoomResponse();
  }

  public static ds.smartbuilding.allocate.meetingRoomResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<meetingRoomResponse>
      PARSER = new com.google.protobuf.AbstractParser<meetingRoomResponse>() {
    @java.lang.Override
    public meetingRoomResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new meetingRoomResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<meetingRoomResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<meetingRoomResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public ds.smartbuilding.allocate.meetingRoomResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

