// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: allocation.proto

package ds.smartbuilding.allocate;

public interface meetingRoomResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:allocate.meetingRoomResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string meetingRoom = 1;</code>
   */
  java.lang.String getMeetingRoom();
  /**
   * <code>string meetingRoom = 1;</code>
   */
  com.google.protobuf.ByteString
      getMeetingRoomBytes();
}
