// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: lighting.proto

package ds.smartbuilding.lighting;

public interface lightResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:lighting.lightResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string msgResponse = 1;</code>
   */
  java.lang.String getMsgResponse();
  /**
   * <code>string msgResponse = 1;</code>
   */
  com.google.protobuf.ByteString
      getMsgResponseBytes();
}
