// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: lighting.proto

package ds.smartbuilding.lighting;

public interface lightOnRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:lighting.lightOnRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string areaCode = 1;</code>
   */
  java.lang.String getAreaCode();
  /**
   * <code>string areaCode = 1;</code>
   */
  com.google.protobuf.ByteString
      getAreaCodeBytes();
}
