// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: temperature.proto

package ds.smartbuilding.temperature;

public interface getTempResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:temperature.getTempResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>double temperature = 1;</code>
   */
  double getTemperature();
}
