// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: temperature.proto

package ds.smartbuilding.temperature;

public interface getTempRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:temperature.getTempRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string areaCode = 1;</code>
   */
  java.lang.String getAreaCode();
  /**
   * <code>string areaCode = 1;</code>
   */
  com.google.protobuf.ByteString
      getAreaCodeBytes();
}
