// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: temperature.proto

package ds.smartbuilding.temperature;

public interface setTempResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:temperature.setTempResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string msgResponse = 1;</code>
   */
  java.lang.String getMsgResponse();
  /**
   * <code>string msgResponse = 1;</code>
   */
  com.google.protobuf.ByteString
      getMsgResponseBytes();
}
