// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: temperature.proto

package ds.smartbuilding.temperature;

public interface setTempRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:temperature.setTempRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string areaCode = 1;</code>
   */
  java.lang.String getAreaCode();
  /**
   * <code>string areaCode = 1;</code>
   */
  com.google.protobuf.ByteString
      getAreaCodeBytes();

  /**
   * <code>double temperature = 2;</code>
   */
  double getTemperature();
}
