// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: access.proto

package ds.smartbuilding.access;

public final class AccessServiceImpl {
  private AccessServiceImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_access_occupantReportRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_access_occupantReportRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_access_occupantReportResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_access_occupantReportResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_access_occupantCheckListRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_access_occupantCheckListRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_access_occupantCheckListResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_access_occupantCheckListResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014access.proto\022\006access\".\n\025occupantReport" +
      "Request\022\025\n\rrequestReport\030\001 \001(\t\"0\n\026occupa" +
      "ntReportResponse\022\026\n\016reportResponse\030\001 \001(\t" +
      "\"/\n\030occupantCheckListRequest\022\023\n\013listOfNa" +
      "mes\030\001 \001(\t\"6\n\031occupantCheckListResponse\022\031" +
      "\n\021checklistResponse\030\001 \001(\t2\304\001\n\rAccessServ" +
      "ice\022S\n\016occupantReport\022\035.access.occupantR" +
      "eportRequest\032\036.access.occupantReportResp" +
      "onse\"\0000\001\022^\n\021occupantCheckList\022 .access.o" +
      "ccupantCheckListRequest\032!.access.occupan" +
      "tCheckListResponse\"\000(\0010\001B.\n\027ds.smartbuil" +
      "ding.accessB\021AccessServiceImplP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_access_occupantReportRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_access_occupantReportRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_access_occupantReportRequest_descriptor,
        new java.lang.String[] { "RequestReport", });
    internal_static_access_occupantReportResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_access_occupantReportResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_access_occupantReportResponse_descriptor,
        new java.lang.String[] { "ReportResponse", });
    internal_static_access_occupantCheckListRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_access_occupantCheckListRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_access_occupantCheckListRequest_descriptor,
        new java.lang.String[] { "ListOfNames", });
    internal_static_access_occupantCheckListResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_access_occupantCheckListResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_access_occupantCheckListResponse_descriptor,
        new java.lang.String[] { "ChecklistResponse", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
