// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: access.proto

package ds.smartbuilding.access;

public interface occupantCheckListRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:access.occupantCheckListRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string listOfNames = 1;</code>
   */
  java.lang.String getListOfNames();
  /**
   * <code>string listOfNames = 1;</code>
   */
  com.google.protobuf.ByteString
      getListOfNamesBytes();
}
