// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: access.proto

package ds.smartbuilding.access;

public interface occupantReportResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:access.occupantReportResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string reportResponse = 1;</code>
   */
  java.lang.String getReportResponse();
  /**
   * <code>string reportResponse = 1;</code>
   */
  com.google.protobuf.ByteString
      getReportResponseBytes();
}
