// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: access.proto

package ds.smartbuilding.access;

public interface occupantReportRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:access.occupantReportRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string requestReport = 1;</code>
   */
  java.lang.String getRequestReport();
  /**
   * <code>string requestReport = 1;</code>
   */
  com.google.protobuf.ByteString
      getRequestReportBytes();
}
