// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: access.proto

package ds.smartbuilding.access;

public interface occupantCheckListResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:access.occupantCheckListResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string checklistResponse = 1;</code>
   */
  java.lang.String getChecklistResponse();
  /**
   * <code>string checklistResponse = 1;</code>
   */
  com.google.protobuf.ByteString
      getChecklistResponseBytes();
}
